Base/Web/Areas/Open/Controllers/HealthController.cs
using Microsoft.AspNetCore.Mvc;

namespace Web.Areas.Open.Controllers
{
    [Area("Open")]
    public class HealthController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}


// https://developer.nutritionix.com/

Base/Web/Areas/Open/Controllers/NewsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Web.Areas.Open.Controllers
{
    [Area("Open")]
    public class NewsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}


// https://newsapi.org/

Base/Web/Areas/Open/Controllers/WeatherController.cs
using Microsoft.AspNetCore.Mvc;

namespace Web.Areas.Open.Controllers
{
    [Area("Open")]
    public class WeatherController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}


// https://openweathermap.org

Base/Web/Areas/Visitor/Controllers/FileController.cs
using DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Models.DataModels;


namespace Web.Areas.Visitor.Controllers
{
    [Area("Visitor")]
    [Authorize]
    public class FileController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;

        public FileController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = hostEnvironment;
        }

        public IActionResult Index()
        {
            List<FileForm> fileFormList = _unitOfWork.FileForm.GetAll().ToList();
            return View(fileFormList);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [RequestSizeLimit(512 * 1024 * 1024)]
        public IActionResult Create(FileForm fileForm, IFormFile? file)
        {

            if (ModelState.IsValid)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (file != null)
                {

                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string filePath = @"Uploads\";
                    string finalPath = Path.Combine(wwwRootPath, filePath);

                    if (!Directory.Exists(finalPath))
                        Directory.CreateDirectory(finalPath);

                    using (var fileStream = new FileStream(Path.Combine(finalPath, fileName), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                    fileForm.FileField = fileName;

                }
                _unitOfWork.FileForm.Add(fileForm);
                _unitOfWork.Save();
                TempData["success"] = "File submitted successfully";
                return RedirectToAction(nameof(Success));
            }
            return View();
        }


        public IActionResult Edit(int? id)
        {
            if (id == null | id == 0)
            {
                return NotFound();
            }

            FileForm? dbFileForm = _unitOfWork.FileForm.GetFirstOrDefault(x => x.Id == id);
            return View(dbFileForm);
        }

        [HttpPost]
        public IActionResult Edit(FileForm fileForm, IFormFile? file)
        {

            if (ModelState.IsValid)
            {
                
                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (file != null)
                {
                    
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string filePath = @"Uploads\";
                    string finalPath = Path.Combine(wwwRootPath, filePath);

                    if (!Directory.Exists(finalPath))
                        Directory.CreateDirectory(finalPath);
                    if (fileForm.FileField != "")
                    {
                        using (var fileStream = new FileStream(Path.Combine(finalPath, fileForm.FileField), FileMode.Create))
                        {
                            file.CopyTo(fileStream);
                        }
                    } 
                    else
                    {
                        using (var fileStream = new FileStream(Path.Combine(finalPath, fileName), FileMode.Create))
                        {
                            file.CopyTo(fileStream);
                        }
                        fileForm.FileField = fileName;
                    }
                }
                _unitOfWork.FileForm.Update(fileForm);
                _unitOfWork.Save();
                TempData["success"] = "File updated successfully";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public IActionResult Delete(int? id)
        {
            if (id == null | id == 0)
            {
                return NotFound();
            }
            FileForm? dbFileForm = _unitOfWork.FileForm.GetFirstOrDefault(x => x.Id == id);
            return View(dbFileForm);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            FileForm? dbFileForm = _unitOfWork.FileForm.GetFirstOrDefault(x => x.Id == id);
            if (dbFileForm == null)
            {
                return NotFound();
            }
            _unitOfWork.FileForm.Delete(dbFileForm.Id);
            _unitOfWork.Save();
            TempData["success"] = "File deleted successfully";
            return RedirectToAction(nameof(Index));
        }



        public ActionResult Success()
        {
            return View();
        }
    }
}

Base/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootstrapTheme.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                File Managment
                            </a>
                            <ul class="dropdown-menu">
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="Visitor" asp-controller="File" asp-action="Index">Files</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" asp-area="Visitor" asp-controller="Screen" asp-action="Index">Screens</a>
                                </li>

                            </ul>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Schedule Managment
                            </a>
                            <ul class="dropdown-menu">
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="Visitor" asp-controller="Calendar" asp-action="Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="Visitor" asp-controller="Calendar" asp-action="BackgroundEvent">Background Event</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="Visitor" asp-controller="Calendar" asp-action="DaygridViews">DaygridViews</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="Visitor" asp-controller="Calendar" asp-action="ExternalDraggingTwoCals">ExternalDraggingTwoCals</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="Visitor" asp-controller="Calendar" asp-action="ExternalDraggingBuiltIn">ExternalDraggingBuiltIn</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="Visitor" asp-controller="Calendar" asp-action="FullHeight">FullHeight</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="Visitor" asp-controller="Calendar" asp-action="ListStickyHeader">ListStickyHeader</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="Visitor" asp-controller="Calendar" asp-action="ListViews">ListViews</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="Visitor" asp-controller="Calendar" asp-action="MonthView">MonthView</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="Visitor" asp-controller="Calendar" asp-action="MultiMonthView">MultiMonthView</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="Visitor" asp-controller="Calendar" asp-action="MultiWeekView">MultiWeekView</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="Visitor" asp-controller="Calendar" asp-action="NaturalHeight">NaturalHeight</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="Visitor" asp-controller="Calendar" asp-action="Selectable">Selectable</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="Visitor" asp-controller="Calendar" asp-action="TimeGridViews">TimeGridViews</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="Visitor" asp-controller="Calendar" asp-action="TimeGridViewsModal">TimeGridViewsModal</a>
                                </li>

                            </ul>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Open Data
                            </a>
                            <ul class="dropdown-menu">
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="Open" asp-controller="Weather" asp-action="Index">Weather</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" asp-area="Open" asp-controller="Location" asp-action="Index">Location</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" asp-area="Open" asp-controller="News" asp-action="Index">News</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="Open" asp-controller="Health" asp-action="Index">Health</a>
                                </li>

                            </ul>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <br />
    <br />
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>
    <br />
    <br />

    @*  <footer class="footer text-muted">
    <div class="container">
    Made with <i class="bi bi-heart-fill"></i> by Smithovision
    </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.15/index.global.min.js'></script>
    <script src="//cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/g6ucaxcx0t9cz5uylrnkgce7qc35c3t2qq4atsqk64fyid3a/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Base/Web/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">toastr.success('@TempData["success"]');</script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">toastr.success('@TempData["success"]');</script>
}