Base/Web/Areas/Admin/Controllers/UserController.cs
using DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Models.IdentityModels;
using Models.UtilityModels;
using Models.ViewModels;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IUnitOfWork _unitOfWork;
        public UserController(UserManager<ApplicationUser> userManager, IUnitOfWork unitOfWork, RoleManager<IdentityRole> roleManager)
        {
            _unitOfWork = unitOfWork;
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult RoleManagment(string userId)
        {

            RoleManagmentVM RoleVM = new RoleManagmentVM()
            {
                ApplicationUser = _unitOfWork.ApplicationUser.Get(u => u.Id == userId),
                RoleList = _roleManager.Roles.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Name
                }),
            };

            RoleVM.ApplicationUser.Role = _userManager.GetRolesAsync(_unitOfWork.ApplicationUser.Get(u => u.Id == userId))
                    .GetAwaiter().GetResult().FirstOrDefault();
            return View(RoleVM);
        }

        [HttpPost]
        public IActionResult RoleManagment(RoleManagmentVM roleManagmentVM)
        {

            string oldRole = _userManager.GetRolesAsync(_unitOfWork.ApplicationUser.Get(u => u.Id == roleManagmentVM.ApplicationUser.Id))
                    .GetAwaiter().GetResult().FirstOrDefault();

            ApplicationUser applicationUser = _unitOfWork.ApplicationUser.Get(u => u.Id == roleManagmentVM.ApplicationUser.Id);

            if (!(roleManagmentVM.ApplicationUser.Role == oldRole))
            {
                //a role was updated
                _unitOfWork.ApplicationUser.Update(applicationUser);
                _unitOfWork.Save();
                _userManager.RemoveFromRoleAsync(applicationUser, oldRole).GetAwaiter().GetResult();
                _userManager.AddToRoleAsync(applicationUser, roleManagmentVM.ApplicationUser.Role).GetAwaiter().GetResult();
            }
            return RedirectToAction("Index");
        }


        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            List<ApplicationUser> objUserList = _unitOfWork.ApplicationUser.GetAll().ToList();

            foreach (var user in objUserList)
            {
                user.Role = _userManager.GetRolesAsync(user).GetAwaiter().GetResult().FirstOrDefault();
            }

            return Json(new { data = objUserList });
        }


        [HttpPost]
        public IActionResult LockUnlock([FromBody] string id)
        {

            var objFromDb = _unitOfWork.ApplicationUser.Get(u => u.Id == id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error while Locking/Unlocking" });
            }

            if (objFromDb.LockoutEnd != null && objFromDb.LockoutEnd > DateTime.Now)
            {
                //user is currently locked and we need to unlock them
                objFromDb.LockoutEnd = DateTime.Now;
            }
            else
            {
                objFromDb.LockoutEnd = DateTime.Now.AddYears(1000);
            }
            _unitOfWork.ApplicationUser.Update(objFromDb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Operation Successful" });
        }

        #endregion
    }
}

Base/Web/Areas/Visitor/Controllers/FileController.cs
using DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Models.DataModels;


namespace Web.Areas.Visitor.Controllers
{
    [Area("Visitor")]
    [Authorize]
    public class FileController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;

        public FileController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = hostEnvironment;
        }

        public IActionResult Index()
        {
            List<FileForm> fileFormList = _unitOfWork.FileForm.GetAll().ToList();
            return View(fileFormList);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [RequestSizeLimit(512 * 1024 * 1024)]
        public IActionResult Create(FileForm fileForm, IFormFile? file)
        {

            if (ModelState.IsValid)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (file != null)
                {

                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string filePath = @"Uploads\";
                    string finalPath = Path.Combine(wwwRootPath, filePath);

                    if (!Directory.Exists(finalPath))
                        Directory.CreateDirectory(finalPath);

                    using (var fileStream = new FileStream(Path.Combine(finalPath, fileName), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                    fileForm.FileField = fileName;

                }
                _unitOfWork.FileForm.Add(fileForm);
                _unitOfWork.Save();
                TempData["success"] = "File submitted successfully";
                return RedirectToAction(nameof(Success));
            }
            return View();
        }


        public IActionResult Edit(int? id)
        {
            if (id == null | id == 0)
            {
                return NotFound();
            }

            FileForm? dbFileForm = _unitOfWork.FileForm.GetFirstOrDefault(x => x.Id == id);
            return View(dbFileForm);
        }

        [HttpPost]
        public IActionResult Edit(FileForm fileForm, IFormFile? file)
        {

            if (ModelState.IsValid)
            {
                
                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (file != null)
                {
                    
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string filePath = @"Uploads\";
                    string finalPath = Path.Combine(wwwRootPath, filePath);

                    if (!Directory.Exists(finalPath))
                        Directory.CreateDirectory(finalPath);
                    if (fileForm.FileField != "")
                    {
                        using (var fileStream = new FileStream(Path.Combine(finalPath, fileForm.FileField), FileMode.Create))
                        {
                            file.CopyTo(fileStream);
                        }
                    } 
                    else
                    {
                        using (var fileStream = new FileStream(Path.Combine(finalPath, fileName), FileMode.Create))
                        {
                            file.CopyTo(fileStream);
                        }
                        fileForm.FileField = fileName;
                    }
                }
                _unitOfWork.FileForm.Update(fileForm);
                _unitOfWork.Save();
                TempData["success"] = "File updated successfully";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public IActionResult Delete(int? id)
        {
            if (id == null | id == 0)
            {
                return NotFound();
            }
            FileForm? dbFileForm = _unitOfWork.FileForm.GetFirstOrDefault(x => x.Id == id);
            return View(dbFileForm);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            FileForm? dbFileForm = _unitOfWork.FileForm.GetFirstOrDefault(x => x.Id == id);
            if (dbFileForm == null)
            {
                return NotFound();
            }
            _unitOfWork.FileForm.Delete(dbFileForm.Id);
            _unitOfWork.Save();
            TempData["success"] = "File deleted successfully";
            return RedirectToAction(nameof(Index));
        }



        public ActionResult Success()
        {
            return View();
        }
    }
}

Base/Web/Areas/Visitor/Controllers/FormController.cs
using DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Models.DataModels;
using Models.IdentityModels;

namespace Web.Areas.Visitor.Controllers
{
    [Area("Visitor")]
    [Authorize]
    public class FormController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        

        public FormController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            List<SampleForm> sampleFormList = _unitOfWork.SampleForm.GetAll().ToList();
            return View(sampleFormList);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(SampleForm sampleForm)
        {

            if (ModelState.IsValid)
            {
                _unitOfWork.SampleForm.Add(sampleForm);
                _unitOfWork.Save();
                TempData["success"] = "Form submitted successfully";
                return RedirectToAction(nameof(Success));
            }
            return View();
        }


        public IActionResult Edit(int? id)
        {
            if (id == null | id == 0)
            {
                return NotFound();
            }

            SampleForm? dbSampleForm = _unitOfWork.SampleForm.GetFirstOrDefault(x => x.Id == id);
            return View(dbSampleForm);
        }

        [HttpPost]
        public IActionResult Edit(SampleForm sampleForm)
        {

            if (ModelState.IsValid)
            {
                _unitOfWork.SampleForm.Update(sampleForm);
                _unitOfWork.Save();
                TempData["success"] = "Form updated successfully";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public IActionResult Delete(int? id)
        {
            if (id == null | id == 0)
            {
                return NotFound();
            }
            SampleForm? dbSampleForm = _unitOfWork.SampleForm.GetFirstOrDefault(x => x.Id == id);
            return View(dbSampleForm);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            SampleForm? category = _unitOfWork.SampleForm.GetFirstOrDefault(x => x.Id == id);
            if (category == null)
            {
                return NotFound();
            }
            _unitOfWork.SampleForm.Delete(category.Id);
            _unitOfWork.Save();
            TempData["success"] = "Form deleted successfully";
            return RedirectToAction(nameof(Index));
        }



        public ActionResult Success()
        {
            return View();
        }
    }
}

Base/Web/Areas/Visitor/Controllers/MultiFileController.cs
using DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Models.DataModels;

namespace Web.Areas.Visitor.Controllers
{
    [Area("Visitor")]
    [Authorize]
    public class MultiFileController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;

        public MultiFileController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = hostEnvironment;
        }

        public IActionResult Index()
        {
            List<MultiFileForm> multiFileFormList = _unitOfWork.MultiFileForm.GetAll().ToList();
            return View(multiFileFormList);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [RequestSizeLimit(512 * 1024 * 1024)]
        public IActionResult Create(MultiFileForm multiFileForm, List<IFormFile>? files)
        {

            if (ModelState.IsValid)
            {
                _unitOfWork.MultiFileForm.Add(multiFileForm);
                _unitOfWork.Save();


                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (files != null)
                {
                    foreach (IFormFile file in files)
                    {
                        string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                        string filePath = @"Uploads\";
                        string finalPath = Path.Combine(wwwRootPath, filePath);

                        if (!Directory.Exists(finalPath))
                            Directory.CreateDirectory(finalPath);

                        using (var fileStream = new FileStream(Path.Combine(finalPath, fileName), FileMode.Create))
                        {
                            file.CopyTo(fileStream);
                        }
                        MultiFile multiFile = new()
                        {
                            FileName = fileName,
                            ContentType = file.ContentType,
                            Size = file.Length,
                            Path = @"\" + filePath + @"\" + fileName,
                            MultiFileFormId = multiFileForm.Id
                        };
                        if (multiFileForm.MultiFiles == null)
                            multiFileForm.MultiFiles = new List<MultiFile>();

                        multiFileForm.MultiFiles.Add(multiFile);

                    }

                
                    _unitOfWork.Save();
                }
                TempData["success"] = "Multiple files submitted successfully";
                return RedirectToAction(nameof(Success));
            }
            return View();
        }


        public IActionResult Edit(int? id)
        {
            if (id == null | id == 0)
            {
                return NotFound();
            }

            FileForm? dbFileForm = _unitOfWork.FileForm.GetFirstOrDefault(x => x.Id == id);
            return View(dbFileForm);
        }

        [HttpPost]
        public IActionResult Edit(FileForm fileForm, IFormFile? file)
        {

            if (ModelState.IsValid)
            {

                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (file != null)
                {

                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string filePath = @"Uploads\";
                    string finalPath = Path.Combine(wwwRootPath, filePath);

                    if (!Directory.Exists(finalPath))
                        Directory.CreateDirectory(finalPath);
                    if (fileForm.FileField != "")
                    {
                        using (var fileStream = new FileStream(Path.Combine(finalPath, fileForm.FileField), FileMode.Create))
                        {
                            file.CopyTo(fileStream);
                        }
                    }
                    else
                    {
                        using (var fileStream = new FileStream(Path.Combine(finalPath, fileName), FileMode.Create))
                        {
                            file.CopyTo(fileStream);
                        }
                        fileForm.FileField = fileName;
                    }
                }
                _unitOfWork.FileForm.Update(fileForm);
                _unitOfWork.Save();
                TempData["success"] = "Multiple files updated successfully";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public IActionResult Delete(int? id)
        {
            if (id == null | id == 0)
            {
                return NotFound();
            }
            FileForm? dbFileForm = _unitOfWork.FileForm.GetFirstOrDefault(x => x.Id == id);
            return View(dbFileForm);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            FileForm? dbFileForm = _unitOfWork.FileForm.GetFirstOrDefault(x => x.Id == id);
            if (dbFileForm == null)
            {
                return NotFound();
            }
            _unitOfWork.FileForm.Delete(dbFileForm.Id);
            _unitOfWork.Save();
            TempData["success"] = "Multiple files deleted successfully";
            return RedirectToAction(nameof(Index));
        }



        public ActionResult Success()
        {
            return View();
        }
    }
}

Base/Web/Areas/Visitor/Views/MultiFile/Create.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@model Models.DataModels.MultiFileForm

@{
    Layout = "_FileLayout";
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>File Form</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="UserId" value="@UserManager.GetUserId(User)" />

            <div class="form-group">
                <label asp-for="TextField" class="control-label"></label>
                <input asp-for="TextField" class="form-control" />
                <span asp-validation-for="TextField" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberField" class="control-label"></label>
                <input asp-for="NumberField" class="form-control" />
                <span asp-validation-for="NumberField" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CheckboxField" class="control-label"></label>
                <input type="checkbox" asp-for="CheckboxField" />
                <span asp-validation-for="CheckboxField" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateField" class="control-label"></label>
                <input asp-for="DateField" class="form-control" />
                <span asp-validation-for="DateField" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DropdownField" class="control-label"></label>
                <select asp-for="DropdownField">
                    <option disabled selected>--Select Option--</option>
                    <option>Option 1</option>
                    <option>Option 2</option>
                    <option>Option 3</option>
                </select>
                <span asp-validation-for="DropdownField" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RadioField" class="control-label"></label><br>
                <input type="radio" id="option1" name="RadioField" value="Option1">
                <label for="Option1">Option 1</label>
                <input type="radio" id="option2" name="RadioField" value="Option2">
                <label for="option2">Option 2</label>
                <input type="radio" id="option3" name="RadioField" value="Option3">
                <label for="option3">Option 3</label>
                <span asp-validation-for="RadioField" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailField" class="control-label"></label>
                <input asp-for="EmailField" class="form-control" />
                <span asp-validation-for="EmailField" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PasswordField" class="control-label"></label>
                <input asp-for="PasswordField" class="form-control" />
                <span asp-validation-for="PasswordField" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TextAreaField" class="control-label"></label>
                <input asp-for="TextAreaField" class="form-control" />
                <span asp-validation-for="TextAreaField" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MultiFiles"></label>
                <input type="file" id="uploadBox" name="file" class="form-control" multiple />
            </div>
            <div class="row">
                <div class="col-6-md-3">
                    <button type="submit" class="btn btn-primary form-control">Create</button>
                </div>
                <div class="col-6-md-3">
                    <a asp-area="Visitor" asp-controller="File" asp-action="Index">Back to List</a>
                </div>
            </div>
        </form>
    </div>
</div>

Base/Web/Areas/Visitor/Views/MultiFile/Delete.cshtml
@{
    Layout = "_FileLayout";
}

Base/Web/Areas/Visitor/Views/MultiFile/Edit.cshtml
@{
    Layout = "_FileLayout";
}

Base/Web/Areas/Visitor/Views/MultiFile/Index.cshtml
@model List<MultiFileForm>
@{
    Layout = "_FileLayout";
}

<div class="container">

    <div class="row pt-4 pb-3">

        <div class="col-6">
            <h2 class="text-primary"> Multi File List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-area="Visitor" asp-controller="MultiFile" asp-action="Create" class="btn btn-primary"><i class="bi bi-plus-circle"></i> Create New MultiFile</a>
        </div>
    </div>


    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>TextField</th>
                <th>NumberField</th>
                <th>Checkbox Field</th>
                <th>Date Field</th>
                <th>Dropdown Field</th>
                <th>Radio Field</th>
                <th>Email Field</th>
                <th>Password Field</th>
                <th>Text Area  Field</th>
                <th>Multi File Field</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td>@obj.TextField</td>
                    <td>@obj.NumberField</td>
                    <td>@obj.CheckboxField</td>
                    <td>@obj.DateField</td>
                    <td>@obj.DropdownField</td>
                    <td>@obj.RadioField</td>
                    <td>@obj.EmailField</td>
                    <td>@obj.PasswordField</td>
                    <td>@obj.TextAreaField</td>
                    <td><img class="fileUploadImage" src="~/Uploads/@obj.MultiFiles.FirstOrDefault())" /></td>
                    <td>
                        <div class="w-75 btnbtn-group" role="group">
                            <a asp-area="Visitor" asp-controller="MultiFile" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary"><i class="bi bi-pencil-square"></i>Edit</a>
                            <a asp-area="Visitor" asp-controller="MultiFile" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger"><i class="bi bi-trash-fill"></i>Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Base/Web/Areas/Visitor/Views/MultiFile/Success.cshtml
@{
    Layout = "_FileLayout";
    ViewBag.Title = "MultiFile Submission Success";
}

<h2>MultiFile Submission Success</h2>

<p>Your files has been submitted successfully!</p>

Base/Web/Areas/Visitor/Views/MultiFile/_FileLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Basics</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">

                        <li class="nav-item">
                            <a class="nav-link" asp-area="Visitor" asp-controller="Form" asp-action="Index">Forms</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="Visitor" asp-controller="File" asp-action="Index">Files</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="Visitor" asp-controller="MultiFile" asp-action="Index">MultiFiles</a>
                        </li>
                        
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Managment
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create User</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">Manage User</a>
                                    </li>

                                </ul>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Made with <i class="bi bi-heart-fill"></i> by Smithovision
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/g6ucaxcx0t9cz5uylrnkgce7qc35c3t2qq4atsqk64fyid3a/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>